// M5 重拍：注入 chip 保留文字
import WebSocket from "ws";
import fs from "node:fs";
const OUT = "D:/dev/cc-watch/.tmp-043/after/";
const TOKEN = "a5aa50d0e0f54a0ea7d13f63b26fc068";
const URL = "http://127.0.0.1:8823/index.html";
const list = await (await fetch("http://127.0.0.1:9223/json/list")).json();
const tgt = list.find((t) => t.type === "page" && t.url.includes("8823")) || list.find((t) => t.type === "page");
const ws = new WebSocket(tgt.webSocketDebuggerUrl);
let seq = 0; const pend = new Map();
const send = (m, p = {}) => new Promise((r) => { const id = ++seq; pend.set(id, r); ws.send(JSON.stringify({ id, method: m, params: p })); });
ws.on("message", (d) => { const m = JSON.parse(String(d)); if (m.id && pend.has(m.id)) { pend.get(m.id)(m.result); pend.delete(m.id); } });
await new Promise((r) => ws.on("open", r));
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const ev = async (e) => (await send("Runtime.evaluate", { expression: e, returnByValue: true })).result?.value;
const style = async (css) => ev(`(function(){document.getElementById("patch")?.remove();var s=document.createElement("style");s.id="patch";s.textContent=${JSON.stringify(css)};document.head.appendChild(s);return "ok";})()`);
await send("Page.enable");
await send("Emulation.setDeviceMetricsOverride", { width: 1280, height: 860, deviceScaleFactor: 1, mobile: false });
await send("Page.navigate", { url: URL });
await sleep(1000);
await ev(`localStorage.setItem("ccd_servers", JSON.stringify([{id:"v1",name:"本机验收",kind:"lan",wsUrl:"ws://127.0.0.1:8787/ws",token:"${TOKEN}"}])); localStorage.removeItem("ccr_theme"); "ok"`);
await send("Page.navigate", { url: URL });
await sleep(2800);
await ev(`document.getElementById("toast")?.classList.remove("show"); "ok"`);
await ev(`(function(){var cs=[...document.querySelectorAll("#cards .card")];(cs.find(x=>x.textContent.includes("0.4.3"))||cs[0]).click();return "ok";})()`);
await sleep(1500);
await ev(`[...document.querySelectorAll(".tabs .tab")].find(x=>x.dataset.tab==="activity")?.click(); "ok"`);
await sleep(800);
await style(`#sendBtn{background:#D97757 !important;color:#fff !important;border:none} #stopBtn{background:#21262d !important;color:#8b949e !important;border:none !important;box-shadow:none} #imgBtn{background:#21262d !important;color:#8b949e !important;border:none !important}`);
console.log(await ev(`(function(){var b=document.getElementById("stopBtn");if(b){b.textContent="■ 注入 Esc";}return "ok";})()`));
await sleep(500);
const img = (await send("Page.captureScreenshot", { format: "png" })).data;
fs.writeFileSync(OUT + "M5.png", Buffer.from(img, "base64"));
console.log("shot: M5");
ws.close();
process.exit(0);
